# A dockerized badgr-server stack to emulate a production build
version: "3.9"
services:

  change-ownership:
    image: alpine
    user: root
    group_add:
      - "999"
    volumes:
      - badgr_server_api_sock:/badgr_server/sock
      - badgr_server_staticfiles:/badgr_server/staticfiles
      - badgr_server_mediafiles:/badgr_server/mediafiles
    command: chown -R 999:999 /badgr_server/sock /badgr_server/staticfiles /badgr_server/mediafiles

  # this container copies in the project code and runs the app with uwsgi
  api:
    build:
      context: .
      dockerfile: .docker/Dockerfile.prod.api
    depends_on:
      db:
        condition: service_started
      memcached:
        condition: service_started
    volumes:
      - badgr_server_api_sock:/badgr_server/sock
      - badgr_server_mediafiles:/badgr_server/mediafiles
      - badgr_server_staticfiles:/badgr_server/staticfiles
    networks:
      - badgr

  # this container runs memcached
  memcached:
    image: "bitnami/memcached:latest"
    expose:
      - "11211"
    networks:
      - badgr

  # this container runs mysql (database)
  db:
    image: mysql:5.7.31
    volumes:
      - badgr_server_prod_db:/var/lib/mysql:rw
      - ./.docker/etc/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - "MYSQL_PASSWORD=password"
      - "MYSQL_HOST=db"
      - "MYSQL_ROOT_PASSWORD=password"
    expose:
      - "3306"
    networks:
      - badgr

  # this container runs nginx (webserver) and uses the uwsgi app.sock file from prod_api via a volume
  nginx:
    build:
      context: .
      dockerfile: .docker/Dockerfile.nginx
    group_add:
      - "999"
    volumes:
      - badgr_server_api_sock:/sock
      - badgr_server_mediafiles:/mediafiles
      - badgr_server_staticfiles:/staticfiles
    depends_on:
      - "api"
    networks:
      - badgr
    ports:
      - "8080:80"

networks:
  badgr:
    driver: bridge

volumes:
  badgr_server_api_sock:
  badgr_server_mediafiles:
  badgr_server_staticfiles:
  badgr_server_prod_db:
