name: ğŸ—‘ï¸ Purge Pull Request Image

# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
# Purge Pull Request Image if pull request gets closed
on:
  pull_request:
    types: [closed]

permissions:
  packages: write

jobs:
  purge_pr_image:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ’£ Purge Pull Request Image
        uses: vlaurin/action-ghcr-prune@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN}}
          organization: ${{ github.repository_owner}}
          container: ${{ github.event.repository.name }}
          prune-tags-regexes: pr-${{github.event.pull_request.number}}$